import { Kategorija } from "../Models/Kategorija.js";

const categories = [
	{
		kategorija_id: 1,
		kategorija: "Spletna trgovina",
		stars_id: 0,
		stars_ime: null,
		marza: null,
	},
	{
		kategorija_id: 17,
		kategorija: "Računalništvo",
		stars_id: 1,
		stars_ime: "Spletna trgovina",
		marza: null,
	},
	{
		kategorija_id: 19,
		kategorija: "Zvok in slika",
		stars_id: 1,
		stars_ime: "Spletna trgovina",
		marza: null,
	},
	{
		kategorija_id: 18,
		kategorija: "Bela tehnika",
		stars_id: 1,
		stars_ime: "Spletna trgovina",
		marza: null,
	},
	{
		kategorija_id: 150,
		kategorija: "Dom in vrt",
		stars_id: 1,
		stars_ime: "Spletna trgovina",
		marza: null,
	},
	{
		kategorija_id: 293,
		kategorija: "Šport in prosti čas",
		stars_id: 1,
		stars_ime: "Spletna trgovina",
		marza: null,
	},
	{
		kategorija_id: 25,
		kategorija: "Prenosniki",
		stars_id: 17,
		stars_ime: "Računalništvo",
		marza: null,
	},
	{
		kategorija_id: 26,
		kategorija: "Namizni računalniki",
		stars_id: 17,
		stars_ime: "Računalništvo",
		marza: null,
	},
	{
		kategorija_id: 35,
		kategorija: "Mini",
		stars_id: 17,
		stars_ime: "Računalništvo",
		marza: null,
	},
	{
		kategorija_id: 33,
		kategorija: "All in One",
		stars_id: 17,
		stars_ime: "Računalništvo",
		marza: null,
	},
	{
		kategorija_id: 36,
		kategorija: "Tablični računalniki",
		stars_id: 17,
		stars_ime: "Računalništvo",
		marza: null,
	},
	{
		kategorija_id: 37,
		kategorija: "Strežniki",
		stars_id: 17,
		stars_ime: "Računalništvo",
		marza: null,
	},
	{
		kategorija_id: 38,
		kategorija: "NAS sistemi",
		stars_id: 17,
		stars_ime: "Računalništvo",
		marza: null,
	},
	{
		kategorija_id: 39,
		kategorija: "Monitorji",
		stars_id: 17,
		stars_ime: "Računalništvo",
		marza: null,
	},
	{
		kategorija_id: 40,
		kategorija: "Komponente",
		stars_id: 17,
		stars_ime: "Računalništvo",
		marza: null,
	},
	{
		kategorija_id: 41,
		kategorija: "Mrežna oprema",
		stars_id: 17,
		stars_ime: "Računalništvo",
		marza: null,
	},
	{
		kategorija_id: 42,
		kategorija: "Tiskanje in optično branje",
		stars_id: 17,
		stars_ime: "Računalništvo",
		marza: null,
	},
	{
		kategorija_id: 43,
		kategorija: "Zunanje naprave",
		stars_id: 17,
		stars_ime: "Računalništvo",
		marza: null,
	},
	{
		kategorija_id: 163,
		kategorija: "Gaming",
		stars_id: 17,
		stars_ime: "Računalništvo",
		marza: null,
	},
	{
		kategorija_id: 162,
		kategorija: "Programska oprema",
		stars_id: 17,
		stars_ime: "Računalništvo",
		marza: null,
	},
    {
        kategorija_id: 195,
        kategorija: "Kripto denarnice",
        stars_id: 17,
        stars_ime: "Računalništvo",
        marza: null,
    },
	{
		kategorija_id: 50,
		kategorija: "Pranje in sušenje",
		stars_id: 18,
		stars_ime: "Bela tehnika",
		marza: null,
	},
	{
		kategorija_id: 51,
		kategorija: "Pomivanje",
		stars_id: 18,
		stars_ime: "Bela tehnika",
		marza: null,
	},
	{
		kategorija_id: 52,
		kategorija: "Hlajenje in zamrzovanje",
		stars_id: 18,
		stars_ime: "Bela tehnika",
		marza: null,
	},
	{
		kategorija_id: 53,
		kategorija: "Kuhanje in pečenje",
		stars_id: 18,
		stars_ime: "Bela tehnika",
		marza: null,
	},
	{
		kategorija_id: 45,
		kategorija: "Televizije",
		stars_id: 19,
		stars_ime: "Zvok in slika",
		marza: null,
	},
	{
		kategorija_id: 46,
		kategorija: "Fotoaparati",
		stars_id: 19,
		stars_ime: "Zvok in slika",
		marza: null,
	},
	{
		kategorija_id: 126,
		kategorija: "Radio in budilke",
		stars_id: 19,
		stars_ime: "Zvok in slika",
		marza: null,
	},
	{
		kategorija_id: 282,
		kategorija: "HI-FI in Prenosni zvočniki",
		stars_id: 19,
		stars_ime: "Zvok in slika",
		marza: null,
	},
	// 2. ai vnos
	{
		kategorija_id: 283,
		kategorija: "Domači kino",
		stars_id: 19,
		stars_ime: "Zvok in slika",
		marza: null,
	},
	{
		kategorija_id: 49,
		kategorija: "Video nadzor",
		stars_id: 19,
		stars_ime: "Zvok in slika",
		marza: null,
	},
	{
		kategorija_id: 240,
		kategorija: "Projekcija",
		stars_id: 19,
		stars_ime: "Zvok in slika",
		marza: null,
	},
	{
		kategorija_id: 241,
		kategorija: "Projektorji",
		stars_id: 240,
		stars_ime: "Projekcija",
		marza: null,
	},
	{
		kategorija_id: 242,
		kategorija: "Projekcijska platna",
		stars_id: 240,
		stars_ime: "Projekcija",
		marza: null,
	},
	{
		kategorija_id: 243,
		kategorija: "Nosilci za projektorje",
		stars_id: 240,
		stars_ime: "Projekcija",
		marza: null,
	},
	{
		kategorija_id: 244,
		kategorija: "Žarnice za projektorje",
		stars_id: 240,
		stars_ime: "Projekcija",
		marza: null,
	},
	{
		kategorija_id: 54,
		kategorija: "Mikrovalovne pečice",
		stars_id: 20,
		stars_ime: "Mali gospodinjski aparati",
		marza: null,
	},
	{
		kategorija_id: 57,
		kategorija: "Mesoreznice in salamoreznice",
		stars_id: 20,
		stars_ime: "Mali gospodinjski aparati",
		marza: null,
	},
	{
		kategorija_id: 58,
		kategorija: "Cvrtniki",
		stars_id: 20,
		stars_ime: "Mali gospodinjski aparati",
		marza: null,
	},
	{
		kategorija_id: 287,
		kategorija: "Kuhalniki",
		stars_id: 20,
		stars_ime: "Mali gospodinjski aparati",
		marza: null,
	},
	{
		kategorija_id: 60,
		kategorija: "Grelniki vode",
		stars_id: 20,
		stars_ime: "Mali gospodinjski aparati",
		marza: null,
	},
	{
		kategorija_id: 61,
		kategorija: "Kuhinjski roboti",
		stars_id: 20,
		stars_ime: "Mali gospodinjski aparati",
		marza: null,
	},
	{
		kategorija_id: 62,
		kategorija: "Kuhinjski žari",
		stars_id: 20,
		stars_ime: "Mali gospodinjski aparati",
		marza: null,
	},
	{
		kategorija_id: 63,
		kategorija: "Mešalniki",
		stars_id: 20,
		stars_ime: "Mali gospodinjski aparati",
		marza: null,
	},
	{
		kategorija_id: 64,
		kategorija: "Opekači kruha",
		stars_id: 20,
		stars_ime: "Mali gospodinjski aparati",
		marza: null,
	},
	{
		kategorija_id: 68,
		kategorija: "Sokovniki in ožemalniki",
		stars_id: 20,
		stars_ime: "Mali gospodinjski aparati",
		marza: null,
	},
	{
		kategorija_id: 67,
		kategorija: "Aparati za peko kruha",
		stars_id: 20,
		stars_ime: "Mali gospodinjski aparati",
		marza: null,
	},
	{
		kategorija_id: 69,
		kategorija: "Vakuumski aparati",
		stars_id: 20,
		stars_ime: "Mali gospodinjski aparati",
		marza: null,
	},
	{
		kategorija_id: 236,
		kategorija: "Multipraktiki",
		stars_id: 20,
		stars_ime: "Mali gospodinjski aparati",
		marza: null,
	},
	{
		kategorija_id: 161,
		kategorija: "Priprava kave in čaja",
		stars_id: 20,
		stars_ime: "Mali gospodinjski aparati",
		marza: null,
	},
	{
		kategorija_id: 153,
		kategorija: "Sušilci sadja",
		stars_id: 20,
		stars_ime: "Mali gospodinjski aparati",
		marza: null,
	},
	{
		kategorija_id: 146,
		kategorija: "Posoda",
		stars_id: 20,
		stars_ime: "Mali gospodinjski aparati",
		marza: null,
	},
	{
		kategorija_id: 207,
		kategorija: "Prenosna kuhališča",
		stars_id: 20,
		stars_ime: "Mali gospodinjski aparati",
		marza: null,
	},
	{
		kategorija_id: 158,
		kategorija: "Ledomat",
		stars_id: 20,
		stars_ime: "Mali gospodinjski aparati",
		marza: null,
	},
	{
		kategorija_id: 143,
		kategorija: "Tehtnice",
		stars_id: 20,
		stars_ime: "Mali gospodinjski aparati",
		marza: null,
	},
	{
		kategorija_id: 116,
		kategorija: "Likalniki",
		stars_id: 20,
		stars_ime: "Mali gospodinjski aparati",
		marza: null,
	},
	{
		kategorija_id: 118,
		kategorija: "Sesalniki",
		stars_id: 20,
		stars_ime: "Mali gospodinjski aparati",
		marza: null,
	},
	{
		kategorija_id: 303,
		kategorija: "Dodatki za prenosnike",
		stars_id: 25,
		stars_ime: "Prenosniki",
		marza: null,
	},
	{
		kategorija_id: 75,
		kategorija: "Osnovne plošče",
		stars_id: 40,
		stars_ime: "Komponente",
		marza: null,
	},
	{
		kategorija_id: 76,
		kategorija: "Procesorji",
		stars_id: 40,
		stars_ime: "Komponente",
		marza: null,
	},
	{
		kategorija_id: 77,
		kategorija: "Pomnilniki",
		stars_id: 40,
		stars_ime: "Komponente",
		marza: null,
	},
	{
		kategorija_id: 78,
		kategorija: "Trdi diski",
		stars_id: 40,
		stars_ime: "Komponente",
		marza: null,
	},
	{
		kategorija_id: 79,
		kategorija: "Ohišja",
		stars_id: 40,
		stars_ime: "Komponente",
		marza: null,
	},
	{
		kategorija_id: 80,
		kategorija: "Napajalniki",
		stars_id: 40,
		stars_ime: "Komponente",
		marza: null,
	},
	{
		kategorija_id: 81,
		kategorija: "Grafične kartice",
		stars_id: 40,
		stars_ime: "Komponente",
		marza: null,
	},
	{
		kategorija_id: 82,
		kategorija: "Optične enote",
		stars_id: 40,
		stars_ime: "Komponente",
		marza: null,
	},
	{
		kategorija_id: 170,
		kategorija: "Zvočne kartice",
		stars_id: 40,
		stars_ime: "Komponente",
		marza: null,
	},
	{
		kategorija_id: 202,
		kategorija: "Hlajenje",
		stars_id: 40,
		stars_ime: "Komponente",
		marza: null,
	},
	{
		kategorija_id: 278,
		kategorija: "Usmerjevalniki, stikala in AP",
		stars_id: 41,
		stars_ime: "Mrežna oprema",
		marza: null,
	},
	{
		kategorija_id: 279,
		kategorija: "Mrežne kartice, Antene, WIFI Ojačevalci",
		stars_id: 41,
		stars_ime: "Mrežna oprema",
		marza: null,
	},
	{
		kategorija_id: 209,
		kategorija: "Powerline",
		stars_id: 41,
		stars_ime: "Mrežna oprema",
		marza: null,
	},
	{
		kategorija_id: 280,
		kategorija: "Tiskalniki",
		stars_id: 42,
		stars_ime: "Tiskanje in optično branje",
		marza: null,
	},
	{
		kategorija_id: 128,
		kategorija: "Optični bralniki",
		stars_id: 42,
		stars_ime: "Tiskanje in optično branje",
		marza: null,
	},
	{
		kategorija_id: 213,
		kategorija: "POS in dodatki",
		stars_id: 42,
		stars_ime: "Tiskanje in optično branje",
		marza: null,
	},
	{
		kategorija_id: 91,
		kategorija: "Potrošni material",
		stars_id: 42,
		stars_ime: "Tiskanje in optično branje",
		marza: null,
	},
	{
		kategorija_id: 92,
		kategorija: "Tipkovnice",
		stars_id: 43,
		stars_ime: "Zunanje naprave",
		marza: null,
	},
	{
		kategorija_id: 93,
		kategorija: "Miške",
		stars_id: 43,
		stars_ime: "Zunanje naprave",
		marza: null,
	},
    {
        kategorija_id: 90,
        kategorija: "Podloge",
        stars_id: 43,
        stars_ime: "Zunanje naprave",
        marza: null,
    },
    {
        kategorija_id: 100,
        kategorija: "Kompleti",
        stars_id: 43,
        stars_ime: "Zunanje naprave",
		marza: null,
    },
	{
		kategorija_id: 210,
		kategorija: "Konferenčna oprema",
		stars_id: 43,
		stars_ime: "Zunanje naprave",
		marza: null,
	},
	{
		kategorija_id: 99,
		kategorija: "USB ključki",
		stars_id: 43,
		stars_ime: "Zunanje naprave",
		marza: null,
	},
	{
		kategorija_id: 96,
		kategorija: "Slušalke",
		stars_id: 43,
		stars_ime: "Zunanje naprave",
		marza: null,
	},
	{
		kategorija_id: 95,
		kategorija: "Spletne kamere",
		stars_id: 43,
		stars_ime: "Zunanje naprave",
		marza: null,
	},
	{
		kategorija_id: 101,
		kategorija: "Spominske kartice in čitalci",
		stars_id: 43,
		stars_ime: "Zunanje naprave",
		marza: null,
	},
	{
		kategorija_id: 94,
		kategorija: "Brezprekinitveno napajanje",
		stars_id: 43,
		stars_ime: "Zunanje naprave",
		marza: null,
	},
	{
		kategorija_id: 97,
		kategorija: "Zvočniki",
		stars_id: 43,
		stars_ime: "Zunanje naprave",
		marza: null,
	},
	{
		kategorija_id: 102,
		kategorija: "Mediji",
		stars_id: 43,
		stars_ime: "Zunanje naprave",
		marza: null,
	},
	{
		kategorija_id: 178,
		kategorija: "Nosilci za TV",
		stars_id: 45,
		stars_ime: "Televizije",
		marza: null,
	},
	{
		kategorija_id: 281,
		kategorija: "Objektivi",
		stars_id: 46,
		stars_ime: "Fotoaparati",
		marza: null,
	},
	{
		kategorija_id: 103,
		kategorija: "Snemalniki",
		stars_id: 49,
		stars_ime: "Video nadzor",
		marza: null,
	},
	{
		kategorija_id: 104,
		kategorija: "Kamere",
		stars_id: 49,
		stars_ime: "Video nadzor",
		marza: null,
	},
	{
		kategorija_id: 284,
		kategorija: "Domofoni",
		stars_id: 49,
		stars_ime: "Video nadzor",
		marza: null,
	},
    {
        kategorija_id: 286,
        kategorija: "Nosilci in napajalniki",
        stars_id: 49,
        stars_ime: "Video nadzor",
        marza: null
    },
	{
		kategorija_id: 106,
		kategorija: "Pralni stroji",
		stars_id: 50,
		stars_ime: "Pranje in sušenje",
		marza: null,
	},
	{
		kategorija_id: 107,
		kategorija: "Sušilni stroji",
		stars_id: 50,
		stars_ime: "Pranje in sušenje",
		marza: null,
	},
	{
		kategorija_id: 206,
		kategorija: "Pralno sušilni stroji",
		stars_id: 50,
		stars_ime: "Pranje in sušenje",
		marza: null,
	},
	{
		kategorija_id: 108,
		kategorija: "Pomivalni stroji",
		stars_id: 51,
		stars_ime: "Pomivanje",
		marza: null,
	},
	{
		kategorija_id: 109,
		kategorija: "Hladilniki",
		stars_id: 52,
		stars_ime: "Hlajenje in zamrzovanje",
		marza: null,
	},
	{
		kategorija_id: 110,
		kategorija: "Zamrzovalniki",
		stars_id: 52,
		stars_ime: "Hlajenje in zamrzovanje",
		marza: null,
	},
	{
		kategorija_id: 111,
		kategorija: "Pečice",
		stars_id: 53,
		stars_ime: "Kuhanje in pečenje",
		marza: null,
	},
	{
		kategorija_id: 112,
		kategorija: "Kuhališča",
		stars_id: 53,
		stars_ime: "Kuhanje in pečenje",
		marza: null,
	},
	{
		kategorija_id: 113,
		kategorija: "Kuhalni seti",
		stars_id: 53,
		stars_ime: "Kuhanje in pečenje",
		marza: null,
	},
	{
		kategorija_id: 114,
		kategorija: "Štedilniki",
		stars_id: 53,
		stars_ime: "Kuhanje in pečenje",
		marza: null,
	},
	{
		kategorija_id: 115,
		kategorija: "Nape",
		stars_id: 53,
		stars_ime: "Kuhanje in pečenje",
		marza: null,
	},
	{
		kategorija_id: 120,
		kategorija: "Blenderji",
		stars_id: 63,
		stars_ime: "Mešalniki",
		marza: null,
	},
	// {
	// 	kategorija_id: 121,
	// 	kategorija: "Palični mešalniki",
	// 	stars_id: 63,
	// 	stars_ime: "Mešalniki",
	// 	marza: null,
	// },
	{
		kategorija_id: 122,
		kategorija: "Ročni mešalniki",
		stars_id: 63,
		stars_ime: "Mešalniki",
		marza: null,
	},
	{
		kategorija_id: 123,
		kategorija: "Sekljalniki",
		stars_id: 63,
		stars_ime: "Mešalniki",
		marza: null,
	},
	{
		kategorija_id: 136,
		kategorija: "Osebna nega",
		stars_id: 293,
		stars_ime: "Šport in prosti čas",
		marza: null,
	},
	{
		kategorija_id: 247,
		kategorija: "Brivniki",
		stars_id: 136,
		stars_ime: "Osebna nega",
		marza: null,
	},
	{
		kategorija_id: 139,
		kategorija: "Strižniki",
		stars_id: 136,
		stars_ime: "Osebna nega",
		marza: null,
	},
	{
		kategorija_id: 140,
		kategorija: "Nega las",
		stars_id: 136,
		stars_ime: "Osebna nega",
		marza: null,
	},
	{
		kategorija_id: 138,
		kategorija: "Depilatorji in epilatorji",
		stars_id: 136,
		stars_ime: "Osebna nega",
		marza: null,
	},
	{
		kategorija_id: 141,
		kategorija: "Ustna nega",
		stars_id: 136,
		stars_ime: "Osebna nega",
		marza: null,
	},
	{
		kategorija_id: 168,
		kategorija: "Tehtnice",
		stars_id: 136,
		stars_ime: "Osebna nega",
		marza: null,
	},
	{
		kategorija_id: 204,
		kategorija: "Pripomočki za osebno nego",
		stars_id: 136,
		stars_ime: "Osebna nega",
		marza: null,
	},
	{
		kategorija_id: 148,
		kategorija: "Klime",
		stars_id: 147,
		stars_ime: "Hlajenje in gretje",
		marza: null,
	},
	{
		kategorija_id: 149,
		kategorija: "Ventilatorji",
		stars_id: 147,
		stars_ime: "Hlajenje in gretje",
		marza: null,
	},
	{
		kategorija_id: 154,
		kategorija: "Radiatorji",
		stars_id: 147,
		stars_ime: "Hlajenje in gretje",
		marza: null,
	},
	{
		kategorija_id: 155,
		kategorija: "Razvlažilci zraka",
		stars_id: 147,
		stars_ime: "Hlajenje in gretje",
		marza: null,
	},
	{
		kategorija_id: 156,
		kategorija: "Vlažilci zraka",
		stars_id: 147,
		stars_ime: "Hlajenje in gretje",
		marza: null,
	},
	{
		kategorija_id: 169,
		kategorija: "Bojlerji",
		stars_id: 147,
		stars_ime: "Hlajenje in gretje",
		marza: null,
	},
	{
		kategorija_id: 288,
		kategorija: "Toplotne črpalke",
		stars_id: 147,
		stars_ime: "Hlajenje in gretje",
		marza: null,
	},
	{
		kategorija_id: 289,
		kategorija: "Hranilniki vode",
		stars_id: 147,
		stars_ime: "Hlajenje in gretje",
		marza: null,
	},
	{
		kategorija_id: 20,
		kategorija: "Mali gospodinjski aparati",
		stars_id: 150,
		stars_ime: "Dom in vrt",
		marza: null,
	},
	{
		kategorija_id: 147,
		kategorija: "Hlajenje in gretje",
		stars_id: 150,
		stars_ime: "Dom in vrt",
		marza: null,
	},
	{
		kategorija_id: 151,
		kategorija: "Žari",
		stars_id: 150,
		stars_ime: "Dom in vrt",
		marza: null,
	},
	{
		kategorija_id: 192,
		kategorija: "Naprave za pametni dom",
		stars_id: 150,
		stars_ime: "Dom in vrt",
		marza: null,
	},
	{
		kategorija_id: 290,
		kategorija: "Pametni vrtovi in semena",
		stars_id: 150,
		stars_ime: "Dom in vrt",
		marza: null,
	},
	{
		kategorija_id: 291,
		kategorija: "Pametni vrtovi",
		stars_id: 290,
		stars_ime: "Pametni vrtovi in semena",
		marza: null,
	},
	{
		kategorija_id: 292,
		kategorija: "Semena",
		stars_id: 290,
		stars_ime: "Pametni vrtovi in semena",
		marza: null,
	},
	{
		kategorija_id: 164,
		kategorija: "Konzole",
		stars_id: 163,
		stars_ime: "Gaming",
		marza: null,
	},
	{
		kategorija_id: 235,
		kategorija: "Igre",
		stars_id: 163,
		stars_ime: "Gaming",
		marza: null,
	},
	{
		kategorija_id: 98,
		kategorija: "Igralni pripomočki",
		stars_id: 163,
		stars_ime: "Gaming",
		marza: null,
	},
	{
		kategorija_id: 205,
		kategorija: "Gaming stoli",
		stars_id: 163,
		stars_ime: "Gaming",
		marza: null,
	},
	{
		kategorija_id: 298,
		kategorija: "Športne ure",
		stars_id: 293,
		stars_ime: "Šport in prosti čas",
		marza: null,
	},
	{
		kategorija_id: 294,
		kategorija: "Daljnogledi",
		stars_id: 293,
		stars_ime: "Šport in prosti čas",
		marza: null,
	},
	{
		kategorija_id: 295,
		kategorija: "Kolesa in skuterji",
		stars_id: 293,
		stars_ime: "Šport in prosti čas",
		marza: null,
	},
	{
		kategorija_id: 296,
		kategorija: "Droni in dodatki",
		stars_id: 293,
		stars_ime: "Šport in prosti čas",
		marza: null,
	},
	{
		kategorija_id: 297,
		kategorija: "Čelade",
		stars_id: 293,
		stars_ime: "Šport in prosti čas",
		marza: null,
	},
	{
		kategorija_id: 299,
		kategorija: "Kampiranje",
		stars_id: 293,
		stars_ime: "Šport in prosti čas",
		marza: null,
	},
	{
		kategorija_id: 300,
		kategorija: "Hladilne torbe",
		stars_id: 293,
		stars_ime: "Šport in prosti čas",
		marza: null,
	},
	{
		kategorija_id: 301,
		kategorija: "Termovke",
		stars_id: 293,
		stars_ime: "Šport in prosti čas",
		marza: null,
	},
	{
		kategorija_id: 302,
		kategorija: "Čistilci na tlak in metle",
		stars_id: 293,
		stars_ime: "Šport in prosti čas",
		marza: null,
	},
];

async function insertCategories() {
	try {
		await Kategorija.sequelize.authenticate();

		await Kategorija.bulkCreate(categories, {
			ignoreDuplicates: true,
		});

		console.log("✅ Categories inserted successfully!");
	} catch (err) {
		console.error("❌ Error inserting categories:", err);
	}
}

export { insertCategories };