const xmlCategories = {
    Računalništvo: [
        "Prenosniki",
        "Namizni računalniki",
        "All in One",
        "Mini",
        "Tablični računalniki",
        "Strežniki",
        "NAS sistemi",
        "Monitorji",
        "Komponente",
        "Mrežna oprema",
        "Tiskanje in optično branje",
        "Zunanje naprave",
        "Televizije",
        "Fotoaparati",
        "Video nadzor",
        "Osnovne plošče",
        "Procesorji",
        "Pomnilniki",
        "Trdi diski",
        "Ohišja",
        "Napajalniki",
        "Grafične kartice",
        "Optične enote",
        "Podloge",
        "Potrošni material",
        "Tipkovnice",
        "Miške",
        "Brezprekinitveno napajanje",
        "Spletne kamere",
        "Slušalke",
        "Zvočniki",
        "Igralni pripomočki",
        "USB ključki",
        "Kompleti",
        "Spominske kartice in čitalci",
        "Mediji",
        "Snemalniki",
        "Kamere",
        "Radio in budilke",
        "Optični bralniki",
        "Programska oprema",
        "Gaming",
        "Konzole",
        "Zvočne kartice",
        "Nosilci za TV",
        "Kripto denarnice",
        "Hlajenje",
        "Gaming stoli",
        "Powerline",
        "Konferenčna oprema",
        "POS in dodatki",
        "Igre",
        "Projektorji",
        "Projekcijska platna",
        "Nosilci za projektorje",
        "Žarnice za projektorje",
        "Usmerjevalniki, stikala in AP",
        "Mrežne kartice, Antene, WIFI Ojačevalci",
        "Tiskalniki",
        "Objektivi",
        "HI-FI in Prenosni zvočniki",
        "Domači kino",
        "Domofoni",
        "Nosilci in napajalniki",
        "Dodatki za prenosnike",
    ],
    "BelaTehnika": [
        "Toplotne črpalke",
        "Hranilniki vode",
        "Pametni vrtovi in semena",
        "Pametni vrtovi",
        "Semena",
        "Šport in prosti čas",
        "Daljnogledi",
        "Kolesa in skuterji",
        "Droni in dodatki",
        "Čelade",
        "Športne ure",
        "Kampiranje",
        "Hladilne torbe",
        "Termovke",
        "Čistilci na tlak in metle",
        "Kuhalniki",
        "Pralno sušilni stroji",
        "Prenosna kuhališča",
        "Mikrovalovne pečice",
        "Mesoreznice in salamoreznice",
        "Cvrtniki",
        "Grelniki vode",
        "Kuhinjski roboti",
        "Kuhinjski žari",
        "Mešalniki",
        "Opekači kruha",
        "Aparati za peko kruha",
        "Sokovniki in ožemalniki",
        "Vakuumski aparati",
        "Pralni stroji",
        "Sušilni stroji",
        "Pomivalni stroji",
        "Hladilniki",
        "Zamrzovalniki",
        "Pečice",
        "Kuhališča",
        "Kuhalni seti",
        "Štedilniki",
        "Nape",
        "Likalniki",
        "Sesalniki",
        "Blenderji",
        "Ročni mešalniki",
        "Sekljalniki",
        "Osebna nega",
        "Depilatorji in epilatorji",
        "Strižniki",
        "Nega las",
        "Ustna nega",
        "Tehtnice",
        "Posoda",
        "Hlajenje in gretje",
        "Ledomat",
        "Priprava kave in čaja",
    ],
    "Razno": [
        "Brivniki",
        "Hlajenje in gretje",
        "Klime",
        "Ventilatorji",
        "Žari",
        "Sušilci sadja",
        "Radiatorji",
        "Razvlažilci zraka",
        "Vlažilci zraka",
        "Bojlerji",
        "Naprave za pametni dom",
        "Pripomočki za osebno nego",
    ]
}

export default xmlCategories;